### ISSUE TITLE
Stuck during package installation.

### ISSUE THREAD

**Issue by cnspary** [teamstarter/graphql-node-jobs#86]
**Install Env:**
```
node version: v21.4.0
npm version: v10.2.4
node-graphql-jobs@0.1.3

```
**Problem:**

when I install node-graphql-jobs@0.1.3 by command `npm i node-graphql-jobs@0.1.3`, the **installation process gets stuck and never ends**. CPU usage will rise to 100%. Memory usage will also rise and will never be freed.

Can someone help check this out?

**Comment by vincentdesmares** [comment]
Hi @cnspary,

Our package is now called "@teamstarter/graphql-node-jobs", "node-graphql-jobs" is still on npm for legacy projects.

Please use "npm i @teamstarter/graphql-node-jobs" instead.

Kind regards,

V.
